export const QUERY_PATHS = {
  GET_ALL_COMPANIES: "GET_ALL_COMPANIES",
  GET_ALL_LOCATIONS_BY_COMPANY_ID: "GET_ALL_LOCATIONS_BY_COMPANY_ID",
  GET_ALL_ASSETS_BY_COMPANY_ID: "GET_ALL_ASSETS_BY_COMPANY_ID",
} as const;
